### ISSUE TITLE
v1.2_2018-11-28 is now available!!

### ISSUE THREAD

**Issue by golife-sysop** [GO-LiFE/GoFIT_SDK_iOS#2]
Dear Developers,

We managed to release the v1.2_2018-11-28 version. This release adds support to GOLiFE's GoWatch series as well as new features such as `find phone`, `find smart-band`, `incoming message notifications`, and `remote shutters` (release notes [here](../releases/tag/v1.2_2018-11-28)).

Kindly check it~

Many thanks.

-- GOLiFE GoFIT SDK Team.

**Comment by piglier** [comment]
在使用2.New Pairing 遇到的情況如下圖 可是不知道要輸入什麼？
再煩請抽空解答感謝！
![unadjustednonraw_thumb_9c](https://user-images.githubusercontent.com/45963571/54022389-5879f700-41cd-11e9-9d8e-9c69d1262b12.jpg)

**Comment by rik296** [comment]
Hi, 這是指掃描到的裝置列表，您可輸入 1 (代表第一個裝置)，來進行配對

**Comment by s1013660s** [comment]
請問開啟 Xcode 專案，是需要使用哪一個開發軟體?
麻煩你了，謝謝。

**Comment by rik296** [comment]
Xcode 是 Apple 公司出的 IDE 工具，您可以透過您 Mac 機器上的 App Store 來下載：
https://itunes.apple.com/tw/app/xcode/id497799835?mt=12

**Comment by golife-sysop** [comment]
Suppose this issue can be closed. Many thanks.
