### ISSUE TITLE
nrf52832_CARE_Xe.hex檔案錯誤

### ISSUE THREAD

**Issue by larryvisuals** [GO-LiFE/GoFIT_SDK_iOS#4]
編譯DemoApp時，出現錯誤nrf52832_CARE_Xe.hex: No such file or directory，想請問nrf52832_CARE_Xe.hex這個檔案是否可以提供，謝謝。

**Comment by rik296** [comment]
Hi，您好，這個 hex file 是我們用來對客戶展示手環 OTA 韌體更新功能使用的，通常是有客製化手環需求的客戶才會只用到此功能與檔案，一般市售手環已搭載好量產的韌體，不需再額外進行韌體更新，所以在我們的 Demo app 專案環境中，您可以將 EmbededFiles 目錄底下的 `binary_list.json` 、`nrf52832_CARE_Xe.hex` 、 `nrf52832_CARE_Xc.hex` 的項目移除，僅留 `client_cert.crt` 即可，移除之後應可編譯成功，造成您操作的不便，敬請見諒 🙏

**Comment by larryvisuals** [comment]
目前將DemoApp中nrf52832_CARE_Xe.hex相關引用移除已可以正常編譯了，感謝。
