### ISSUE TITLE
libGoFIT_SDK.a出現缺少arm64架構錯誤

### ISSUE THREAD

**Issue by larryvisuals** [GO-LiFE/GoFIT_SDK_iOS#5]
加入libGoFIT_SDK.a後編譯出現錯誤訊息，是否有哪些地方還需要做設定。

`Undefined symbols for architecture arm64:
  "___gxx_personality_v0", referenced from:
      l102 in libGoFIT_SDK.a
      l104 in libGoFIT_SDK.a
      l105 in libGoFIT_SDK.a
      l107 in libGoFIT_SDK.a
      l108 in libGoFIT_SDK.a
      l112 in libGoFIT_SDK.a
      l113 in libGoFIT_SDK.a
      ...
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by rik296** [comment]
Hi, 您好，您可以檢查一下在 Linked Frameworks and Libraries 區塊，是否有加入 `libGoFIT_SDK.a`、`libz.tbd`、`libxml2.tbd` 這三個 library，或許可以解決您的問題
![68747470733a2f2f692e696d6775722e636f6d2f6c4d39613973572e706e67](https://user-images.githubusercontent.com/16934269/67824592-caf36a80-fb01-11e9-823e-bb8c2e6f08f5.png)

**Comment by rik296** [comment]
另外，在 `Build Settings` 頁籤，`Other Linker Flag` 欄位可填入 `-lstdc++` 、 `-ObjC`

**Comment by larryvisuals** [comment]
在 Build Settings 頁籤設定後，已可以成功編譯，感謝。
